server:
  port: 8082

spring:
  application:
    name: reservas
  datasource:
    url: jdbc:mysql://localhost:3306/bd_veterinaria_reservas?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false